AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI-Photo-Album

Resources:
  frontendbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: frontend-photoalbum-cloudformation
      WebsiteConfiguration:
        IndexDocument: index.html
  frontendbucketpolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
            - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${frontendbucket}/*'
      Bucket: !Ref frontendbucket
  backendbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: backend-photoalbum-cloudformation
  backendbucketpolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
            - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${backendbucket}/*'
      Bucket: !Ref backendbucket
  lambda1:
    Type: AWS::Lambda::Function
    Properties:
      Code: 
        ZipFile: >
                def lambda_handler(event, context):
                return 'Hello from Lambda'
      Description: Lambda with CF
      FunctionName: LambdaWithCF
      Handler: index.lambda_handler
      Role: arn:aws:iam::568808643890:role/LambdaRole
      Runtime: python3.9
      

      
